# Generated by Django 4.1.7 on 2023-03-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=2)),
                ('region', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
