# Generated by Django 4.1.7 on 2023-03-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provinciasCrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincias',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='provincias',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='provincias',
            old_name='superficie',
            new_name='surface',
        ),
    ]
