# Generated by Django 4.1.7 on 2023-04-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinciasCrud', '0004_cities_provinces_region_delete_provincias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinces',
            name='density',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provinces',
            name='population',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provinces',
            name='surface',
            field=models.FloatField(),
        ),
    ]
