# Generated by Django 4.1.7 on 2023-04-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinciasCrud', '0005_provinces_density_provinces_population_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinces',
            name='density',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='population',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='surface',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
