# Generated by Django 4.1.7 on 2023-04-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinciasCrud', '0006_alter_provinces_density_alter_provinces_population_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='population',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
