# Generated by Django 4.1.7 on 2023-04-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinciasCrud', '0007_alter_cities_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinces',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
