# Generated by Django 4.1.7 on 2023-04-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinciasCrud', '0008_alter_provinces_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinces',
            name='density',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='population',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='surface',
            field=models.FloatField(),
        ),
    ]
